# Autogenerated wrapper script for spla_jll for aarch64-apple-darwin-mpi+mpitrampoline
export libspla

using libblastrampoline_jll
using LLVMOpenMP_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("spla")
JLLWrappers.@declare_library_product(libspla, "@rpath/libspla.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, LLVMOpenMP_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libspla,
        "lib/libspla.1.5.5.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
